

apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiftcart-frontend
  labels:
    app: swiftcart-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swiftcart-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: swiftcart-frontend
    spec:
      containers:
      - name: swiftcart-frontend
        image: <ACR_NAME>.azurecr.io/swiftcart-frontend:latest
        ports:
        - containerPort: 3000
       


---
apiVersion: v1
kind: Service
metadata:
  name: svc-swiftcart-frontend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: swiftcart-frontend